# C:\Users\smkar\.streamlit\secrets.toml
# OR C:\Users\smkar\aoe-motors-dashboard-frontend\.streamlit\secrets.toml

SUPABASE_URL = "https://zihoocpsvadiwrcqbrxf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppaG9vY3BzdmFkaXdyY3FicnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTg4MTksImV4cCI6MjA2NzEzNDgxOX0.kdC31j0rnbmJ7qVuNh6p3pzMiqHSq-xITAfG8Sp8qQA"
EMAIL_HOST = "smtp.gmail.com" # e.g., smtp.gmail.com
EMAIL_PORT = 4655 # or 465 for SSL, depends on your host
EMAIL_ADDRESS = "sm.karthikeyan31@gmail.com"
EMAIL_PASSWORD = "jsvx nfmb zpfe afwn" # For Gmail, use App Password, not your regular password